; BIND reverse data file for empty rfc1918 zone
;
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
$TTL    86400
@       IN      SOA     ns1.domain-registrar.publicvm.com. admin.domain-registrar.publicvm.com (
                              2         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                          86400 )       ; Negative Cache TTL
;
domain-registrar.publicvm.com.     IN      NS      ns1.domain-registrar.publicvm.com.
domain-registrar.publicvm.com.     IN      NS      ns2.domain-registrar.publicvm.com.
ns1.domain-registrar.publicvm.com. IN      A       54.215.83.143
ns2.domain-registrar.publicvm.com. IN      A       59.9.123.61
domain-registrar.publicvm.com.     IN      A       54.177.232.250
www.domain-registrar.publicvm.com. IN      A       54.177.232.250
cp.domain-registrar.publicvm.com.	IN	A	54.177.232.250
whois.domain-registrar.publicvm.com.	IN	A	54.177.232.250
rdap.domain-registrar.publicvm.com.	IN	A	54.177.232.250
